/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Jinal
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        universityModelSplitPanel = new javax.swing.JSplitPane();
        universityWorkingAreaPanel = new javax.swing.JPanel();
        lblAdminModuleText = new javax.swing.JLabel();
        btnViewColleges = new javax.swing.JButton();
        btnViewDepartments = new javax.swing.JButton();
        btnViewCourses = new javax.swing.JButton();
        btnViewClasses = new javax.swing.JButton();
        btnViewEnrollments = new javax.swing.JButton();
        btnViewStudentDetails = new javax.swing.JButton();
        btnViewFacultyDetails = new javax.swing.JButton();
        btnViewStudentEmploymentDetails = new javax.swing.JButton();
        btnViewStudentFeedbackForm = new javax.swing.JButton();
        btnViewDashboardForCourses = new javax.swing.JButton();
        universityActionArea = new javax.swing.JPanel();
        lblNEUUniversity = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        universityModelSplitPanel.setBackground(new java.awt.Color(0, 153, 153));
        universityModelSplitPanel.setDividerLocation(230);
        universityModelSplitPanel.setPreferredSize(new java.awt.Dimension(1393, 775));

        universityWorkingAreaPanel.setBackground(new java.awt.Color(0, 153, 153));

        lblAdminModuleText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdminModuleText.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminModuleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminModuleText.setText("Admin Module");

        btnViewColleges.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewColleges.setText("View Colleges");
        btnViewColleges.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewColleges.setBorderPainted(false);
        btnViewColleges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCollegesActionPerformed(evt);
            }
        });

        btnViewDepartments.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewDepartments.setText("View Departments");
        btnViewDepartments.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewDepartments.setBorderPainted(false);
        btnViewDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDepartmentsActionPerformed(evt);
            }
        });

        btnViewCourses.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewCourses.setText("View Courses");
        btnViewCourses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewCourses.setBorderPainted(false);
        btnViewCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCoursesActionPerformed(evt);
            }
        });

        btnViewClasses.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewClasses.setText("View Classes");
        btnViewClasses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewClasses.setBorderPainted(false);
        btnViewClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewClassesActionPerformed(evt);
            }
        });

        btnViewEnrollments.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewEnrollments.setText("View Enrollments/Registrations");
        btnViewEnrollments.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewEnrollments.setBorderPainted(false);
        btnViewEnrollments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEnrollmentsActionPerformed(evt);
            }
        });

        btnViewStudentDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewStudentDetails.setText("View Student Details");
        btnViewStudentDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewStudentDetails.setBorderPainted(false);
        btnViewStudentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentDetailsActionPerformed(evt);
            }
        });

        btnViewFacultyDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewFacultyDetails.setText("View Faculty Details");
        btnViewFacultyDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewFacultyDetails.setBorderPainted(false);
        btnViewFacultyDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFacultyDetailsActionPerformed(evt);
            }
        });

        btnViewStudentEmploymentDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewStudentEmploymentDetails.setText("View Student Employment Deatils");
        btnViewStudentEmploymentDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewStudentEmploymentDetails.setBorderPainted(false);
        btnViewStudentEmploymentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentEmploymentDetailsActionPerformed(evt);
            }
        });

        btnViewStudentFeedbackForm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewStudentFeedbackForm.setText("View Student Feedback Form");
        btnViewStudentFeedbackForm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewStudentFeedbackForm.setBorderPainted(false);
        btnViewStudentFeedbackForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentFeedbackFormActionPerformed(evt);
            }
        });

        btnViewDashboardForCourses.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewDashboardForCourses.setText("View Dashboard for Courses");
        btnViewDashboardForCourses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnViewDashboardForCourses.setBorderPainted(false);
        btnViewDashboardForCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDashboardForCoursesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout universityWorkingAreaPanelLayout = new javax.swing.GroupLayout(universityWorkingAreaPanel);
        universityWorkingAreaPanel.setLayout(universityWorkingAreaPanelLayout);
        universityWorkingAreaPanelLayout.setHorizontalGroup(
            universityWorkingAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(universityWorkingAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(universityWorkingAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewEnrollments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewStudentDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewFacultyDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewStudentEmploymentDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(btnViewStudentFeedbackForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(universityWorkingAreaPanelLayout.createSequentialGroup()
                        .addGroup(universityWorkingAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnViewColleges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewDepartments, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(btnViewCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblAdminModuleText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewDashboardForCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        universityWorkingAreaPanelLayout.setVerticalGroup(
            universityWorkingAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(universityWorkingAreaPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblAdminModuleText)
                .addGap(31, 31, 31)
                .addComponent(btnViewColleges, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewDepartments, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewEnrollments, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewStudentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewFacultyDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewStudentEmploymentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewStudentFeedbackForm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnViewDashboardForCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        universityModelSplitPanel.setLeftComponent(universityWorkingAreaPanel);

        universityActionArea.setBackground(new java.awt.Color(0, 153, 153));

        lblNEUUniversity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNEUUniversity.setForeground(new java.awt.Color(255, 255, 255));
        lblNEUUniversity.setText("Northeastern University Model");

        javax.swing.GroupLayout universityActionAreaLayout = new javax.swing.GroupLayout(universityActionArea);
        universityActionArea.setLayout(universityActionAreaLayout);
        universityActionAreaLayout.setHorizontalGroup(
            universityActionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(universityActionAreaLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(lblNEUUniversity, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(513, Short.MAX_VALUE))
        );
        universityActionAreaLayout.setVerticalGroup(
            universityActionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(universityActionAreaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblNEUUniversity)
                .addContainerGap(721, Short.MAX_VALUE))
        );

        universityModelSplitPanel.setRightComponent(universityActionArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(universityModelSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(universityModelSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCoursesActionPerformed
        // TODO add your handling code here:
        
        ViewCoursePanel viewCoursePanel = new ViewCoursePanel();
        universityModelSplitPanel.setRightComponent(viewCoursePanel);
    }//GEN-LAST:event_btnViewCoursesActionPerformed

    private void btnViewCollegesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCollegesActionPerformed
        // TODO add your handling code here:
        ViewCollegePanel viewCollegePanel = new ViewCollegePanel();
        universityModelSplitPanel.setRightComponent(viewCollegePanel);
    }//GEN-LAST:event_btnViewCollegesActionPerformed

    private void btnViewDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDepartmentsActionPerformed
        // TODO add your handling code here:
        ViewDepartmentPanel viewDepartmentPanel = new ViewDepartmentPanel();
        universityModelSplitPanel.setRightComponent(viewDepartmentPanel);
    }//GEN-LAST:event_btnViewDepartmentsActionPerformed

    private void btnViewClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewClassesActionPerformed
        // TODO add your handling code here:
        ViewClassesPanel viewClassesPanel = new ViewClassesPanel();
        universityModelSplitPanel.setRightComponent(viewClassesPanel);
    }//GEN-LAST:event_btnViewClassesActionPerformed

    private void btnViewEnrollmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEnrollmentsActionPerformed
        // TODO add your handling code here:
        
        ViewEnrollmentDetailsPanel viewEnrollmentDetailsPanel = new ViewEnrollmentDetailsPanel();
        universityModelSplitPanel.setRightComponent(viewEnrollmentDetailsPanel);
    }//GEN-LAST:event_btnViewEnrollmentsActionPerformed

    private void btnViewStudentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentDetailsActionPerformed
        // TODO add your handling code here:
        
        ViewStudentDetailsPanel viewStudentDetailsPanel = new ViewStudentDetailsPanel();
        universityModelSplitPanel.setRightComponent(viewStudentDetailsPanel);
    }//GEN-LAST:event_btnViewStudentDetailsActionPerformed

    private void btnViewFacultyDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFacultyDetailsActionPerformed
        // TODO add your handling code here:
        
        ViewFacultyDetailsPanel viewFacultyDetailsPanel = new ViewFacultyDetailsPanel();
        universityModelSplitPanel.setRightComponent(viewFacultyDetailsPanel);
    }//GEN-LAST:event_btnViewFacultyDetailsActionPerformed

    private void btnViewStudentEmploymentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentEmploymentDetailsActionPerformed
        // TODO add your handling code here:
     
        ViewStudentEmploymentDeatilsPanel viewStudentEmploymentDeatilsPanel = new ViewStudentEmploymentDeatilsPanel();
        universityModelSplitPanel.setRightComponent(viewStudentEmploymentDeatilsPanel);
    }//GEN-LAST:event_btnViewStudentEmploymentDetailsActionPerformed

    private void btnViewStudentFeedbackFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentFeedbackFormActionPerformed
        // TODO add your handling code here:
        
        ViewStudentFeedbackDetailsPanel viewStudentFeedbackDetailsPanel = new ViewStudentFeedbackDetailsPanel();
        universityModelSplitPanel.setRightComponent(viewStudentFeedbackDetailsPanel);
    }//GEN-LAST:event_btnViewStudentFeedbackFormActionPerformed

    private void btnViewDashboardForCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDashboardForCoursesActionPerformed
        // TODO add your handling code here:
        ViewDashboardForCoursesBasedOnEmployment viewDashboardForCoursesBasedOnEmployment = new ViewDashboardForCoursesBasedOnEmployment();
       universityModelSplitPanel.setRightComponent(viewDashboardForCoursesBasedOnEmployment);
    }//GEN-LAST:event_btnViewDashboardForCoursesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewClasses;
    private javax.swing.JButton btnViewColleges;
    private javax.swing.JButton btnViewCourses;
    private javax.swing.JButton btnViewDashboardForCourses;
    private javax.swing.JButton btnViewDepartments;
    private javax.swing.JButton btnViewEnrollments;
    private javax.swing.JButton btnViewFacultyDetails;
    private javax.swing.JButton btnViewStudentDetails;
    private javax.swing.JButton btnViewStudentEmploymentDetails;
    private javax.swing.JButton btnViewStudentFeedbackForm;
    private javax.swing.JLabel lblAdminModuleText;
    private javax.swing.JLabel lblNEUUniversity;
    private javax.swing.JPanel universityActionArea;
    private javax.swing.JSplitPane universityModelSplitPanel;
    private javax.swing.JPanel universityWorkingAreaPanel;
    // End of variables declaration//GEN-END:variables
}
