/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jinal
 */
public class ViewCoursePanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCollegePanel
     */
    public ViewCoursePanel() {
        initComponents();
       generateTableForListOfCourses();
    }
    
    
        private void generateTableForListOfCourses()
     {
         DefaultTableModel dtm = (DefaultTableModel)tblViewCoursePanel.getModel();
         
        Object row[] = new Object[3];
         
        
         dtm.setRowCount(0);
                          
           row[0] = "5100";
           row[1] = "Application Engineering Development";
           row[2] = "Information Systems";    
           dtm.addRow(row);
           
           
           row[0] = "6150";
           row[1] = "Web Design and UX Engineering";
           row[2] = "Information Systems";    
           dtm.addRow(row);
           
           row[0] = "5150";
           row[1] = "Concepts of Object Oriented Design";
           row[2] = "Software Engineering";    
           dtm.addRow(row);
           
           row[0] = "5200";
           row[1] = "Program structures and algorithms";
           row[2] = "Software Engineering";    
           dtm.addRow(row);
         
           row[0] = "5250";
           row[1] = "DWBI";
           row[2] = "Information Systems";    
           dtm.addRow(row);
           
        
           row[0] = "5300";
           row[1] = "Data Science Engineering methods and tools";
           row[2] = "DAMG";    
           dtm.addRow(row);
           
           row[0] = "5350";
           row[1] = "Web Development tools";
           row[2] = "Information Systems";    
           dtm.addRow(row);
           
           row[0] = "5400";
           row[1] = "Big Data Engineering";
           row[2] = "DAMG";    
           dtm.addRow(row);
                       
           row[0] = "5450";
           row[1] = "Cloud computing";
           row[2] = "Information Systems";    
           dtm.addRow(row);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewCoursePanel = new javax.swing.JTable();
        lblViewListOfCourses = new javax.swing.JLabel();
        lblViewEmploymentBasedOnCourses = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        tblViewCoursePanel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Unique ID", "Course Name", "Department Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewCoursePanel);

        lblViewListOfCourses.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblViewListOfCourses.setForeground(new java.awt.Color(255, 255, 255));
        lblViewListOfCourses.setText("View List of Courses");

        lblViewEmploymentBasedOnCourses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/employment_based_on_courses.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lblViewListOfCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblViewEmploymentBasedOnCourses)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewListOfCourses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblViewEmploymentBasedOnCourses)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewEmploymentBasedOnCourses;
    private javax.swing.JLabel lblViewListOfCourses;
    private javax.swing.JTable tblViewCoursePanel;
    // End of variables declaration//GEN-END:variables
}
