/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jinal
 */
public class ViewDepartmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCollegePanel
     */
    public ViewDepartmentPanel() {
        initComponents();
        
        generateTableForListOfDepartments();
    }
    
    
        private void generateTableForListOfDepartments()
     {
         DefaultTableModel dtm = (DefaultTableModel)tblViewDepartmentPanel.getModel();
         
        Object row[] = new Object[3];
         
        
         dtm.setRowCount(0);
                          
           row[0] = "1";
           row[1] = "Information Systems";
           row[2] = "Kal bugara";   
           dtm.addRow(row);
           
           
           row[0] = "2";
           row[1] = "DAMG";
           row[2] = "Nick Brown";    
           dtm.addRow(row);
           
           row[0] = "3";
           row[1] = "Software Engineering";
           row[2] = "Robin Hillyard";    
           dtm.addRow(row);
           
           row[0] = "4";
           row[1] = "Data Analytics Engineering";
           row[2] = "Vishal Chawla";    
           dtm.addRow(row);

        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewDepartmentPanel = new javax.swing.JTable();
        lblViewListOfDepartments = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        tblViewDepartmentPanel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Department Unique ID", "Department Name", "Department Head"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewDepartmentPanel);

        lblViewListOfDepartments.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblViewListOfDepartments.setForeground(new java.awt.Color(255, 255, 255));
        lblViewListOfDepartments.setText("View List of Departments");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(lblViewListOfDepartments, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblViewListOfDepartments)
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(412, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewListOfDepartments;
    private javax.swing.JTable tblViewDepartmentPanel;
    // End of variables declaration//GEN-END:variables
}
