/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Jinal
 */
public class ViewDashboardForCoursesBasedOnEmployment extends javax.swing.JPanel {

    /**
     * Creates new form ViewCollegePanel
     */
    public ViewDashboardForCoursesBasedOnEmployment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewListOfEmploymentTypeBasedOnCourses = new javax.swing.JLabel();
        lblViewStudentEmploymentTypeBasedOnCoursesDashboard = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        lblViewListOfEmploymentTypeBasedOnCourses.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblViewListOfEmploymentTypeBasedOnCourses.setForeground(new java.awt.Color(255, 255, 255));
        lblViewListOfEmploymentTypeBasedOnCourses.setText("View Employment Type based on Courses");

        lblViewStudentEmploymentTypeBasedOnCoursesDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/employment_type_based_on_courses.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(lblViewListOfEmploymentTypeBasedOnCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(838, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblViewStudentEmploymentTypeBasedOnCoursesDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 1351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblViewListOfEmploymentTypeBasedOnCourses)
                .addGap(36, 36, 36)
                .addComponent(lblViewStudentEmploymentTypeBasedOnCoursesDashboard)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblViewListOfEmploymentTypeBasedOnCourses;
    private javax.swing.JLabel lblViewStudentEmploymentTypeBasedOnCoursesDashboard;
    // End of variables declaration//GEN-END:variables
}
