/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jinal
 */
public class ViewEnrollmentDetailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCollegePanel
     */
    public ViewEnrollmentDetailsPanel() {
        initComponents();
        
        generateTableForListOfEnrollments();
    }

         private void generateTableForListOfEnrollments()
     {
         DefaultTableModel dtm = (DefaultTableModel)tblViewEnrollemntPanel.getModel();
         
        Object row[] = new Object[5];
         
        
         dtm.setRowCount(0);
                          
           row[0] = "1";
           row[1] = "1";
           row[2] = "Application Engineering Development";
           row[3] = "450"; 
           row[4] = "12"; 
           dtm.addRow(row);
           
          row[0] = "2";
           row[1] = "2";
           row[2] = "Web Design and UX Engineering";
           row[3] = "40"; 
           row[4] = "3"; 
           dtm.addRow(row);
           
         
            row[0] = "3";
           row[1] = "3";
           row[2] = "Web Design and UX Engineering";
           row[3] = "140"; 
           row[4] = "14"; 
           dtm.addRow(row);
           
           
           row[0] = "4";
           row[1] = "4";
           row[2] = "Concepts of Object Oriented Design";
           row[3] = "60"; 
           row[4] = "3"; 
           dtm.addRow(row);
           
           
           row[0] = "5";
           row[1] = "5";
           row[2] = "Program Structures Algorithm";
           row[3] = "90"; 
           row[4] = "8"; 
           dtm.addRow(row);
           
           
             
           row[0] = "6";
           row[1] = "6";
           row[2] = "Program Structures Algorithm";
           row[3] = "65"; 
           row[4] = "4"; 
           dtm.addRow(row);
           
           
              
           row[0] = "7";
           row[1] = "7";
           row[2] = "DWBI";
           row[3] = "50"; 
           row[4] = "2"; 
           dtm.addRow(row);
           
           row[0] = "8";
           row[1] = "8";
           row[2] = "DWBI";
           row[3] = "60"; 
           row[4] = "2"; 
           dtm.addRow(row);
           
           row[0] = "9";
           row[1] = "9";
           row[2] = "Data Science Engineering methods and tools";
           row[3] = "76"; 
           row[4] = "6"; 
           dtm.addRow(row);
           
           row[0] = "10";
           row[1] = "10";
           row[2] = "Data Science Engineering methods and tools";
           row[3] = "55"; 
           row[4] = "5"; 
           dtm.addRow(row);
           
              row[0] = "11";
           row[1] = "11";
           row[2] = "Web Development tools";
           row[3] = "65"; 
           row[4] = "4"; 
           dtm.addRow(row);
           
            row[0] = "12";
           row[1] = "12";
           row[2] = "Big Data Engineering";
           row[3] = "45"; 
           row[4] = "2"; 
           dtm.addRow(row);  
           
           row[0] = "13";
           row[1] = "13";
           row[2] = "Cloud computing";
           row[3] = "50"; 
           row[4] = "2"; 
           dtm.addRow(row);
           
           row[0] = "14";
           row[1] = "14";
           row[2] = "Web Development tools";
           row[3] = "55"; 
           row[4] = "3"; 
           dtm.addRow(row);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewEnrollemntPanel = new javax.swing.JTable();
        lblViewListOfEnrollments = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        tblViewEnrollemntPanel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Enrollment Unique ID", "Class Name", "Course Name", "Total Enrollment Count", "Waiting Count"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewEnrollemntPanel);

        lblViewListOfEnrollments.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblViewListOfEnrollments.setForeground(new java.awt.Color(255, 255, 255));
        lblViewListOfEnrollments.setText("View List of Enrollments");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/student_employment_small_dashboard.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(lblViewListOfEnrollments, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblViewListOfEnrollments)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewListOfEnrollments;
    private javax.swing.JTable tblViewEnrollemntPanel;
    // End of variables declaration//GEN-END:variables
}
