/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jinal
 */
public class ViewCollegePanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCollegePanel
     */
    public ViewCollegePanel() {
        initComponents();
        generateTableForListOfColleges();
    }
  private void generateTableForListOfColleges()
     {
         DefaultTableModel dtm = (DefaultTableModel)tblViewCollege.getModel();
         
        Object row[] = new Object[2];
         
        
         dtm.setRowCount(0);
                          
           row[0] = "1";
           row[1] = "College of Engineering";
           dtm.addRow(row);       
           
           row[0] = "2";
           row[1] = "Khoury college of computer Science"; 
           dtm.addRow(row);
           
           row[0] = "3";
           row[1] = "School of Pharmacy";
           dtm.addRow(row);
           
           row[0] = "4";
           row[1] = "College of Professional studies";
           dtm.addRow(row);
         
           row[0] = "5";
           row[1] = "School of law";
           dtm.addRow(row);
           
        
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewCollege = new javax.swing.JTable();
        lblViewListOfColleges = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        tblViewCollege.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "College Unique ID", "Colllege Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewCollege);

        lblViewListOfColleges.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblViewListOfColleges.setForeground(new java.awt.Color(255, 255, 255));
        lblViewListOfColleges.setText("View List of Colleges");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(lblViewListOfColleges, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblViewListOfColleges)
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewListOfColleges;
    private javax.swing.JTable tblViewCollege;
    // End of variables declaration//GEN-END:variables
}
